name: flutter_drift_sample
description: "Drift Flutter Sample"
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  drift: ^2.14.1
  path: ^1.8.3
  path_provider: ^2.1.1
  sqlite3: ^2.3.0
  sqlite3_flutter_libs: ^0.5.18
  equatable: ^2.0.5


dev_dependencies:
  build_runner: ^2.4.7
  drift_dev: ^2.14.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
